import { DropdownFieldModel } from '../interfaces/DropdownFieldModel';
import { DateFieldModel } from '../interfaces/DateFieldModel';
import { TodoItemCategoryEnum } from '../../api';
import { TodoItemPriorityEnum } from '../../api';
import { TodoItemTodoStatusEnum } from '../../api';
import { TodoItem } from '../../api';
import { TableHeaderModel } from '../interfaces/TableHeaderModel';
import { InputFieldModel } from '../interfaces/InputFieldModel';

class TasksData {
  public static tableHeaders: TableHeaderModel<TodoItem>[] = [
    { id: 'title', label: 'Title', sortable: true, type: 'string' },
    { id: 'actions', label: 'Actions', sortable: false, type: 'action' },
    { id: 'batchId', label: 'Batch Id', sortable: true, type: 'number' },
    {
      id: 'autoGenerated',
      label: 'Autogenerated',
      sortable: true,
      type: 'number',
    },
    { id: 'priority', label: 'Priority', sortable: true, type: 'string' },
    { id: 'category', label: 'Category', sortable: true, type: 'string' },
    { id: 'todoStatus', label: 'Status', sortable: true, type: 'string' },
    { id: 'dueDate', label: 'Due Date', sortable: true, type: 'date' },
  ];

  public static textFields: Record<string, InputFieldModel> = {
    searchQuery: { key: 'searchQuery', label: 'Search', defaultValue: '' },
    descriptionField: {
      key: 'description',
      label: 'Notes',
      defaultValue: '',
    },
  };

  public static dropdowns: Record<string, DropdownFieldModel> = {
    autoGenerated: {
      key: 'autoGenerated',
      label: 'Auto Generated',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      defaultValue: '',
    },
    category: {
      key: 'category',
      label: 'Category',
      options: Object.values(TodoItemCategoryEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
    priority: {
      key: 'priority',
      label: 'Priority',
      options: Object.values(TodoItemPriorityEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
    todoStatus: {
      key: 'todoStatus',
      label: 'Status',
      options: Object.values(TodoItemTodoStatusEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
  };

  public static dateFields: DateFieldModel[] = [
    { key: 'startDate', label: 'Start Date', defaultValue: '' },
    { key: 'endDate', label: 'End Date', defaultValue: '' },
  ];
}

export default TasksData;
