import { DropdownFieldModel } from '../interfaces/DropdownFieldModel';
import { DateFieldModel } from '../interfaces/DateFieldModel';
import { TodoItemCategoryEnum } from '../../api';
import { TodoItemPriorityEnum } from '../../api';
import { TodoItemTodoStatusEnum } from '../../api';
import { TodoItem } from '../../api';
import { TableHeaderModel } from '../interfaces/TableHeaderModel';
import { InputFieldModel } from '../interfaces/InputFieldModel';

class TasksData {
  public static tableHeaders: TableHeaderModel<TodoItem>[] = [
    {
      id: 'title',
      label: 'Task Name',
      sortable: true,
      type: 'string',
      tooltip: 'The title of the task',
    },
    {
      id: 'batchId',
      label: 'Batch Id',
      sortable: true,
      type: 'number',
      tooltip: 'Use this identifier to link the reading to a batch',
    },
    {
      id: 'actions',
      label: 'Actions',
      sortable: false,
      type: 'action',
      tooltip: 'View, edit or delete the task',
    },
    {
      id: 'autoGenerated',
      label: 'Autogenerated',
      sortable: true,
      type: 'boolean',
      tooltip: 'Did the application generate this task automatically?',
    },
    {
      id: 'priority',
      label: 'Priority',
      sortable: true,
      type: 'string',
      tooltip: 'The priority of the task',
    },
    {
      id: 'category',
      label: 'Category',
      sortable: true,
      type: 'string',
      tooltip: 'The category of the task',
    },
    {
      id: 'todoStatus',
      label: 'Status',
      sortable: true,
      type: 'string',
      tooltip: 'The current status of the task',
    },
    {
      id: 'dueDate',
      label: 'Due Date',
      sortable: true,
      type: 'date',
      tooltip: 'The date when the task is due',
    },
  ];

  public static textFieldsString: Record<string, InputFieldModel> = {
    searchQuery: { key: 'searchQuery', label: 'Search', defaultValue: '' },
    descriptionField: {
      key: 'description',
      label: 'Notes',
      defaultValue: '',
    },
  };

  public static dropdowns: Record<string, DropdownFieldModel> = {
    category: {
      key: 'category',
      label: 'Category',
      options: Object.values(TodoItemCategoryEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
    priority: {
      key: 'priority',
      label: 'Priority',
      options: Object.values(TodoItemPriorityEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
    todoStatus: {
      key: 'todoStatus',
      label: 'Status',
      options: Object.values(TodoItemTodoStatusEnum).map((value) => ({
        value: value,
        label: value,
      })),
      defaultValue: '',
    },
  };

  public static dateFields: DateFieldModel[] = [
    { key: 'startDate', label: 'Due Before', defaultValue: '' },
    { key: 'endDate', label: 'Due After', defaultValue: '' },
  ];
}

export default TasksData;

/*
    autoGenerated: {
      key: 'autoGenerated',
      label: 'Auto Generated',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      defaultValue: '',
    },*/
