name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build the app
        env:
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_PLANT_API_KEY: ${{ secrets.VITE_PLANT_API_KEY }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_REDIRECT_URI: ${{ secrets.VITE_AUTH0_REDIRECT_URI }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        run: npm run build

        # Step 4.1: Add 404.html for routing
      - name: Add 404.html
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8" />
            <title>Page Not Found</title>
            <script>
             // Get the current path without the repository name
             var path = window.location.pathname;

           // Handle paths with or without the repo name prefix
           var basePath = "/GrowHubFrontend";
           var cleanPath = path;

             // Remove the base path if it exists at the beginning
           if (path.indexOf(basePath) === 0) {
           cleanPath = path.replace(basePath, "");
           }

           // Redirect to the root with the hash route
           window.location.href = basePath + "/#" + cleanPath;
          </script>
          </head>
          <body>
            <h1>404 - Page Not Found</h1>
            <p>Redirecting...</p>
          </body>
          </html>' > ./dist/404.html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
